### ISSUE TITLE
GitHub

### ISSUE THREAD

**Issue by ageraldo1** [tajncteam/CSC3210-TAJNC#3]
+ Create GitHub account and name it using the group name chosen before
+ Write the project title and the team members’ names in Readme file under the Code
Tab. Submit a screen shoot of your readme page.
+ Create a new project using the Project Tab and name it CSC3210- group name. Use
the: To do; In progress; and Done columns. Under these columns, create your own cards
and have the assigned tasks and their status (in progress and done) written there as a list.
Submit a screen shoot of your project page

**Comment by tajncteam** [comment]
Assignment completed.
