### ISSUE TITLE
Learning Teamwork Basics

### ISSUE THREAD

**Issue by ageraldo1** [tajncteam/CSC3210-TAJNC#4]
+ What to do to get the task accomplished and the team members’ satisfaction high?
+ Answer all the questions in the Work Norms, Facilitator Norms, Communication
Norms using your own words and your own context
+As a team, select two cases out of the four mentioned in Handling Difficult
Behavior. (use your own words and your own context)
+ When making decisions, If the team is having trouble reaching consensus, what
should you do? (use your own words and your own context)
+ What should you do if person may reach a decision more quickly than others and
pressure people to move on before it is a good idea to do so?
+ What happens if most people on the team want to get an “A” on the assignment, but
another person decides that a “B” will be acceptable?

**Comment by tajncteam** [comment]
Assignment completed.
